version: '3.7'

services:
    master-0:
        image: qiao/ubuntu-18.04:v1
        container_name: master-0
        hostname: master-0
        environment:
            - TZ=Asia/Shanghai
            - JAVA_HOME=/usr/local/jdk1.8.0_261
            - HADOOP_HOME=/root/shared/hadoop-2.10.1
            - HADOOP_CONF_DIR=/root/shared/hadoop-2.10.1/etc/hadoop
        volumes:
            - $PWD/../hosts.temp:/etc/hosts
            - $PWD/../sshd_config.temp:/etc/ssh/sshd_config
            - $PWD/../data-shared:/root/shared
            - $PWD/data/master-0:/root/data
        privileged: true
        ports:
            - "50010:50010"
            - "50020:50020"
            - "50030:50030"
            - "50060:50060"
            - "50070:50070"
            - "50075:50075"
            - "50090:50090"
        tty: true
        networks:
            db_net:
                ipv4_address: 172.21.0.100
        restart: always

    slave-0:
        image: qiao/ubuntu-18.04:v1
        container_name: slave-0
        hostname: slave-0
        environment:
            - TZ=Asia/Shanghai
        volumes:
            - $PWD/../hosts.temp:/etc/hosts
            - $PWD/../sshd_config.temp:/etc/ssh/sshd_config
            - $PWD/../data-shared:/root/shared
            - $PWD/data/slave-0:/root/data
        privileged: true
        tty: true
        networks:
            db_net:
                ipv4_address: 172.21.0.101
        restart: always

    slave-1:
        image: qiao/ubuntu-18.04:v1
        container_name: slave-1
        hostname: slave-1
        environment:
            - TZ=Asia/Shanghai
        volumes:
            - $PWD/../hosts.temp:/etc/hosts
            - $PWD/../sshd_config.temp:/etc/ssh/sshd_config
            - $PWD/../data-shared:/root/shared
            - $PWD/data/slave-1:/root/data
        privileged: true
        tty: true
        networks:
            db_net:
                ipv4_address: 172.21.0.102
        restart: always

networks:
    db_net:
        external: true
        name: db_net

