version: '3.7'

services:

  elasticsearch:
    image: elasticsearch:7.6.1
    container_name: es7_01
    hostname: es7_01
    privileged: true
    environment:
      - cluster.name=data-player
      - node.name=es7_01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - discovery.seed_hosts=es7_01,es7_02
      - cluster.initial_master_nodes=es7_01,es7_02
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data_es7_01:/elasticsearch/data
    ports:
      - "9222:9200"
    networks:
      db_net:
        ipv4_address: 172.21.0.151
    restart: always

  elasticsearch2:
    image: elasticsearch:7.6.1
    container_name: es7_02
    hostname: es7_02
    privileged: true
    environment:
      - cluster.name=data-player
      - node.name=es7_02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - discovery.seed_hosts=es7_01,es7_02
      - cluster.initial_master_nodes=es7_01,es7_02
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data_es7_02:/elasticsearch/data
    networks:
      db_net:
        ipv4_address: 172.21.0.152
    restart: always

  logstash:
    image: logstash:7.6.1
    container_name: logstash7
    hostname: logstash7
    privileged: true
    volumes:
      - "/home/sq/docker/container-volume/logstash7:/logstash7/data"
    networks:
      db_net:
        ipv4_address: 172.21.0.153
    restart: always

  kibana:
    image: kibana:7.6.1
    container_name: kibana7
    hostname: kibana7
    privileged: true
    environment:
      - I18N_LOCALE=zh-CN
      - XPACK_GRAPH_ENABLED=true
      - TIMELION_ENABLED=true
      - XPACK_MONITORING_COLLECTION_ENABLED="true"
    ports:
      - "5601:5601"
    networks:
      db_net:
        ipv4_address: 172.21.0.154
    restart: always

  cerebro:
    image: lmenezes/cerebro:0.8.5
    container_name: cerebro
    hostname: cerebro
    privileged: true
    ports:
      - "9111:9000"
    command:
      - -Dhosts.0.host=http://es7_01:9200
    networks:
      db_net:
        ipv4_address: 172.21.0.155
    restart: always

volumes:
  data_es7_01:
  data_es7_02:

networks:
  db_net:
    external: true
    name: db_net


