version: '3.7'

services:
    flink-0:
        image: qiao/ubuntu-18.04:v1
        container_name: flink-0
        hostname: flink-0
        environment:
            - TZ=Asia/Shanghai
        volumes:
            - $PWD/../hosts.temp:/etc/hosts
            - $PWD/../sshd_config.temp:/etc/ssh/sshd_config
            - $PWD/../data-shared:/root/downloads
            - $PWD/data/flink-0:/root/data
        privileged: true
        tty: true
        networks:
            db_net:
                ipv4_address: 172.21.0.120
        restart: always

networks:
    db_net:
        external: true
        name: db_net
